openapi: "3.0.0"

info:
  title: Dmetric
  description: Application for device metrics monitoring
  version: "0.0.1"
  
tags: 
  - name: Health
  - name: Devices
  
paths:
  /health:
    get:
      tags: 
        - Health
      summary: Checks if the server is alive
      responses: 
        "204":
          description: No content
  
  /api/v1/devices:
    get:
      tags:
        - Devices
      summary: Returns a list of devices and last updated time of each one
      responses:
        "200":
          description: OK
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Devices"
    post:
      tags:
        - Devices
      summary: Creates a new device and returns ID of
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: dev_2
                temperature_enabled:
                  type: boolean
                  example: false
                noisiness_enabled:
                  type: boolean
                  example: false
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"

  /api/v1/devices/:id/metrics:
    get:
      tags:
      - Devices
      summary: Returns a list of metrics by device ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Metrics"
    post:
      tags:
      - Devices
      summary: Devices should send metrics on this endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                temperature:
                  type: integer
                  example: 23
                noisiness:
                  type: integer
                  example: 45         
      responses:
        "201":
          description: Created
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Metric"
        
    
components:
  schemas:
    Devices:
      type: array
      items:
        type: object
        properties:
          id: 
            type: integer
          name:
            type: string
          created_at:
            type: string
            description: time in format RFC3339
          updated_at:
            type: string
            description: time in format RFC3339
          temperature_enabled: 
            type: boolean
          noisiness_enabled:
            type: boolean
          humidity_enabled:
            type: boolean
      example:
        - id: 3
          name: dev_3
          created_at: '2021-12-03'
          updated_at: '2021-18-03'
          temperature_enabled: true
          noisiness_enabled: false
          humidity_enabled: false
        - id: 4
          name: dev_4
          created_at: '2021-12-03'
          temperature_enabled: false
          noisiness_enabled: true
          humidity_enabled: true
    Device:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        temperature_enabled:
          type: boolean
        noisiness_enabled:
          type: boolean
        humidity_enabled:
          type: boolean
        created_at:
          type: string
          description: time in format RFC3339
      example:
          id: 2
          name : dev_2
          temperature_enabled: false
          noisiness_enabled: false
          humidity_enabled: true
          created_at: "2021-03-31T10:43:59.444Z"
    Metrics:
      type: array
      items:
        type: object
        properties:
          temperature:
            type: integer
          noisiness:
            type: integer
          time:
            type: string
            description: time in format RFC3339
      example:
        - temperature: 30
          noisiness: 25
          time: "2021-03-28T16:05:47.706Z"
        - temperature: 22
          noisiness: 20
          time: "2021-03-28T16:10:52.339Z"
    Metric:
      type: object
      properties:
        id: 
          type: integer
          # example: 4
        device_id: 
          type: integer
          # example: 2
        time: 
          type: string
          description: time in format RFC3339
          # example: "2021-03-31T11:01:42.608Z"
        temperature: 
          type: integer
          # example: 23
        noisiness:
          type: integer
          # example: 45
      example:
        id: 4
        device_id: 2
        temperature: 23
        noisiness: 45
        time: "2021-03-31T11:01:42.608Z"
        